// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pkg/proto/rubric.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRubricResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Result                `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRubricResultRequest) Reset() {
	*x = UploadRubricResultRequest{}
	mi := &file_pkg_proto_rubric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRubricResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRubricResultRequest) ProtoMessage() {}

func (x *UploadRubricResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rubric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRubricResultRequest.ProtoReflect.Descriptor instead.
func (*UploadRubricResultRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rubric_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRubricResultRequest) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type UploadRubricResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRubricResultResponse) Reset() {
	*x = UploadRubricResultResponse{}
	mi := &file_pkg_proto_rubric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRubricResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRubricResultResponse) ProtoMessage() {}

func (x *UploadRubricResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rubric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRubricResultResponse.ProtoReflect.Descriptor instead.
func (*UploadRubricResultResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rubric_proto_rawDescGZIP(), []int{1}
}

func (x *UploadRubricResultResponse) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *UploadRubricResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Rubric        []*RubricItem          `protobuf:"bytes,3,rep,name=rubric,proto3" json:"rubric,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	GeoLocation   string                 `protobuf:"bytes,5,opt,name=geo_location,json=geoLocation,proto3" json:"geo_location,omitempty"`
	Project       string                 `protobuf:"bytes,6,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_pkg_proto_rubric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rubric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rubric_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *Result) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Result) GetRubric() []*RubricItem {
	if x != nil {
		return x.Rubric
	}
	return nil
}

func (x *Result) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Result) GetGeoLocation() string {
	if x != nil {
		return x.GeoLocation
	}
	return ""
}

func (x *Result) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type RubricItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	Points        float64                `protobuf:"fixed64,3,opt,name=points,proto3" json:"points,omitempty"`
	Awarded       float64                `protobuf:"fixed64,4,opt,name=awarded,proto3" json:"awarded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RubricItem) Reset() {
	*x = RubricItem{}
	mi := &file_pkg_proto_rubric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RubricItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RubricItem) ProtoMessage() {}

func (x *RubricItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_rubric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RubricItem.ProtoReflect.Descriptor instead.
func (*RubricItem) Descriptor() ([]byte, []int) {
	return file_pkg_proto_rubric_proto_rawDescGZIP(), []int{3}
}

func (x *RubricItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RubricItem) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *RubricItem) GetPoints() float64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *RubricItem) GetAwarded() float64 {
	if x != nil {
		return x.Awarded
	}
	return 0
}

var File_pkg_proto_rubric_proto protoreflect.FileDescriptor

const file_pkg_proto_rubric_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/rubric.proto\x12\x06rubric\"C\n" +
	"\x19UploadRubricResultRequest\x12&\n" +
	"\x06result\x18\x01 \x01(\v2\x0e.rubric.ResultR\x06result\"[\n" +
	"\x1aUploadRubricResultResponse\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd3\x01\n" +
	"\x06Result\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12*\n" +
	"\x06rubric\x18\x03 \x03(\v2\x12.rubric.RubricItemR\x06rubric\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12!\n" +
	"\fgeo_location\x18\x05 \x01(\tR\vgeoLocation\x12\x18\n" +
	"\aproject\x18\x06 \x01(\tR\aproject\"f\n" +
	"\n" +
	"RubricItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\x12\x16\n" +
	"\x06points\x18\x03 \x01(\x01R\x06points\x12\x18\n" +
	"\aawarded\x18\x04 \x01(\x01R\aawarded2l\n" +
	"\rRubricService\x12[\n" +
	"\x12UploadRubricResult\x12!.rubric.UploadRubricResultRequest\x1a\".rubric.UploadRubricResultResponseB(Z&github.com/jh125486/gradebot/pkg/protob\x06proto3"

var (
	file_pkg_proto_rubric_proto_rawDescOnce sync.Once
	file_pkg_proto_rubric_proto_rawDescData []byte
)

func file_pkg_proto_rubric_proto_rawDescGZIP() []byte {
	file_pkg_proto_rubric_proto_rawDescOnce.Do(func() {
		file_pkg_proto_rubric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_rubric_proto_rawDesc), len(file_pkg_proto_rubric_proto_rawDesc)))
	})
	return file_pkg_proto_rubric_proto_rawDescData
}

var file_pkg_proto_rubric_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_rubric_proto_goTypes = []any{
	(*UploadRubricResultRequest)(nil),  // 0: rubric.UploadRubricResultRequest
	(*UploadRubricResultResponse)(nil), // 1: rubric.UploadRubricResultResponse
	(*Result)(nil),                     // 2: rubric.Result
	(*RubricItem)(nil),                 // 3: rubric.RubricItem
}
var file_pkg_proto_rubric_proto_depIdxs = []int32{
	2, // 0: rubric.UploadRubricResultRequest.result:type_name -> rubric.Result
	3, // 1: rubric.Result.rubric:type_name -> rubric.RubricItem
	0, // 2: rubric.RubricService.UploadRubricResult:input_type -> rubric.UploadRubricResultRequest
	1, // 3: rubric.RubricService.UploadRubricResult:output_type -> rubric.UploadRubricResultResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_rubric_proto_init() }
func file_pkg_proto_rubric_proto_init() {
	if File_pkg_proto_rubric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_rubric_proto_rawDesc), len(file_pkg_proto_rubric_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_rubric_proto_goTypes,
		DependencyIndexes: file_pkg_proto_rubric_proto_depIdxs,
		MessageInfos:      file_pkg_proto_rubric_proto_msgTypes,
	}.Build()
	File_pkg_proto_rubric_proto = out.File
	file_pkg_proto_rubric_proto_goTypes = nil
	file_pkg_proto_rubric_proto_depIdxs = nil
}
